[package]
name = "ufs"
version = "0.1.0"
authors = ["uberfoo"]
edition = "2018"

[features]
default  = ["fuse", "hyper", "reqwest", "ring"]

[[bench]]
name = "block-server"
harness = false

[dependencies]
bincode = "1.1.4"
clap = "2.33.0"
crossbeam = "0.7.1"
dotenv = "0.14.1"
failure = "0.1.5"
futures = "0.1.27"
lazy_static = "1.3.0"
libc = "0.2"
log = "0.4.6"
pretty_env_logger = "0.3.0"
rand = "0.7.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2.16"
time = "0.1.42"
wasmi = "0.4.5"
colored = "1.8.0"
rpassword = "4.0.1"
c2-chacha = "0.2.2"
hmac = "0.7.1"
sha2 = "0.8.0"
pbkdf2 = "0.3.0"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[dependencies.fuse]
version = "0.3.1"
optional = true

[dependencies.hyper]
version = "0.12.30"
optional = true

[dependencies.reqwest]
version = "0.9.18"
optional = true

[dependencies.ring]
version = "0.14.6"
optional = true

[dependencies.uuid]
version = "0.7.4"
default-features = false
features = ["v5", "serde"]

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.2.11"
env_logger = "0.6.1"
hex-literal = "0.2.0"
