[package]
name = "ufs"
version = "0.1.0"
authors = ["uberfoo"]
edition = "2018"

[features]
default  = ["fuse", "hyper", "reqwest", "ring"]

[[bench]]
name = "block-server"
harness = false

[dependencies]
bincode = "1.1.4"
clap = "2.33.0"
crossbeam = "0.7.2"
dotenv = "0.14.1"
failure = "0.1.5"
futures = "0.1.28"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4.8"
pretty_env_logger = "0.3.1"
rand = "0.7.0"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.3.0"
time = "0.1.42"
wasmi = "0.5.0"
colored = "1.8.0"
rpassword = "4.0.1"
c2-chacha = "0.2.2"
hmac = "0.7.1"
sha2 = "0.8.0"
pbkdf2 = "0.3.0"

[dependencies.chrono]
version = "0.4.9"
features = ["serde"]

[dependencies.fuse]
version = "0.3.1"
optional = true

[dependencies.hyper]
version = "0.12.33"
optional = true

[dependencies.reqwest]
version = "0.9.20"
optional = true

[dependencies.ring]
version = "0.16.9"
optional = true

[dependencies.uuid]
version = "0.7.4"
default-features = false
features = ["v5", "serde"]

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.3.0"
env_logger = "0.6.2"
hex-literal = "0.2.1"

[profile.test]
opt-level = 3