[package]
name = "ufs"
version = "0.1.0"
authors = ["uberfoo"]
edition = "2018"

[[bench]]
name = "block-server"
harness = false

[dependencies]
bincode = "1.1.3"
env_logger = "0.6.1"
failure = "0.1.5"
fuse = "0.3.1"
futures = "0.1.26"
hyper = "0.12.27"
libc = "0.2"
log = "0.4.6"
pretty_env_logger = "0.3.0"
ring = "0.14.6"
serde = "1.0"
serde_derive = "1.0"
time = "0.1.42"
dotenv = "0.13.0"
lazy_static = "1.3.0"
reqwest = "0.9.15"

[dependencies.uuid]
version = "0.7.4"
default-features = false
features = ["v5", "serde"]

[dev-dependencies]
hex-literal = "0.1"
assert_matches = "1.3.0"
structopt = "0.2.15"
criterion = "0.2.11"
