[package]
name = "ufs"
version = "0.1.0"
authors = ["uberfoo"]
edition = "2018"

[dependencies]
failure = "0.1.5"
ring = "0.14.6"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.1.2"
fuse = "0.3.1"
libc = "0.2"
time = "0.1.42"
log = "0.4.6"

[dev-dependencies]
hex-literal = "0.1"
assert_matches = "1.3.0"
env_logger = "0.6.0"
structopt = "0.2.14"
