[package]
name = "ufs"
version = "0.1.0"
authors = ["uberfoo"]
edition = "2018"

[[bench]]
name = "block-server"
harness = false

[dependencies]
bincode = "1.1.4"
dotenv = "0.14.1"
failure = "0.1.5"
fuse = "0.3.1"
futures = "0.1.27"
hyper = "0.12.29"
lazy_static = "1.3.0"
libc = "0.2"
log = "0.4.6"
pretty_env_logger = "0.3.0"
reqwest = "0.9.17"
ring = "0.14.6"
serde = "1.0"
serde_derive = "1.0"
structopt = "0.2.15"
time = "0.1.42"
wasmi = "0.4.5"

[dependencies.chrono]
version = "0.4.6"
features = ["serde"]

[dependencies.uuid]
version = "0.7.4"
default-features = false
features = ["v5", "serde"]

[dev-dependencies]
assert_matches = "1.3.0"
criterion = "0.2.11"
env_logger = "0.6.1"
hex-literal = "0.2.0"
