[package]
name = "ufs"
version = "0.1.0"
authors = ["uberfoo"]
edition = "2018"

[dependencies]
failure = "0.1.5"
ring = "0.14.4"
serde = "1.0.86"
serde_derive = "1.0.86"
bincode = "1.0.1"

[dev-dependencies]
hex-literal = "0.1.2"
assert_matches = "1.3.0"
