[package]
name = "echo"
version = "0.1.0"
authors = ["Keith T. Star <keith@uberfoo.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.3.0"
mut_static = "5.0.0"

[dependencies.ufs]
default-features = false
path = "../../"